# @format

name: crop_disease_app
description: Crop Disease Detection Platform for Smallholder Farmers

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  camera: ^0.11.3
  speech_to_text: ^7.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  image: ^4.5.4
  file_picker: ^10.3.7
  geolocator: ^13.0.1
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lang/
    - assets/images/
